In [1]:
#Creating Arrays
import numpy as np

# 1D array
arr1 = np.arange(1, 11)
print(arr1)

# 2D array (3x3)
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)

# 3D random array (3,5,3)
arr3 = np.random.rand(3, 5, 3)
print(arr3)

# Shapes, sizes, dtypes
print(arr1.shape, arr1.size, arr1.dtype)
print(arr2.shape, arr2.size, arr2.dtype)
print(arr3.shape, arr3.size, arr3.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[0.2515335  0.10485689 0.07709016]
  [0.53529482 0.87455919 0.49053651]
  [0.95947539 0.24766913 0.38140044]
  [0.70052779 0.54980389 0.65355921]
  [0.86589977 0.90407693 0.29161881]]

 [[0.75982771 0.33678447 0.33271982]
  [0.95809054 0.73976018 0.72783923]
  [0.94141252 0.86428915 0.34202026]
  [0.92241758 0.38502797 0.48830139]
  [0.46676596 0.78502942 0.69369076]]

 [[0.33012213 0.59854256 0.79949644]
  [0.20142262 0.89293368 0.1553844 ]
  [0.55047315 0.87852818 0.25411665]
  [0.40330102 0.37373398 0.09751929]
  [0.30691233 0.37572646 0.11348591]]]
(10,) 10 int64
(3, 3) 9 int64
(3, 5, 3) 45 float64


In [4]:
#Array Indexing and Slicing
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(data[:3])          # First three elements
print(data[::2])         # Every alternate element
print(data[::-1])        # Reverse


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [2]:
# Mathematical Ops
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("A:", A)
print("B:", B)

print("Add:", A + B)
print("Subtract:", A - B)
print("Multiply:", A * B)
print("Divide:", A / B)

print("Dot Product:", np.dot(A, B))

print("A Mean:", np.mean(A))
print("A Median:", np.median(A))
print("A Std:", np.std(A))
print("A Var:", np.var(A))

print("B Max:", np.max(B), "at index", np.argmax(B))
print("B Min:", np.min(B), "at index", np.argmin(B))


A: [18  4 10  7 12]
B: [ 6 18 19 14 14]
Add: [24 22 29 21 26]
Subtract: [ 12 -14  -9  -7  -2]
Multiply: [108  72 190  98 168]
Divide: [3.         0.22222222 0.52631579 0.5        0.85714286]
Dot Product: 636
A Mean: 10.2
A Median: 10.0
A Std: 4.749736834815167
A Var: 22.560000000000002
B Max: 19 at index 2
B Min: 6 at index 0


In [8]:
# Reshaping And Trnasposing
arr = np.arange(1, 13)

arr2d = arr.reshape(4, 3)
print(arr2d)

arr3d = arr.reshape(2, 2, 3)
print(arr3d)

transposed = arr2d.T
print(transposed)
print("Transposed shape:", transposed.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transposed shape: (3, 4)


In [9]:
# Boolean masking and filtering 
arr = np.random.randint(10, 51, 15)
print("Array:", arr)

print("Elements >25:", arr[arr > 25])

arr[arr < 30] = 0
print("After replacing <30 with 0:", arr)

print("Count divisible by 5:", np.sum(arr % 5 == 0))


Array: [43 46 39 26 26 49 19 15 28 12 44 11 12 13 35]
Elements >25: [43 46 39 26 26 49 28 44 35]
After replacing <30 with 0: [43 46 39  0  0 49  0  0  0  0 44  0  0  0 35]
Count divisible by 5: 10


In [ ]:
# Working with built in functions
print(np.linspace(0, 1, 10))

print(np.eye(4))

arr = np.random.randint(1, 101, 20)
arr.sort()
print("Sorted:", arr)
print("5 largest:", arr[-5:])
