In [3]:
#Creating Arrays
import numpy as np

# 1D array
arr1 = np.arange(1, 11)
print(arr1)

# 2D array (3x3)
arr2 = np.arange(1, 10).reshape(3, 3)
print(arr2)

# 3D random array (3,5,3)
arr3 = np.random.rand(3, 5, 3)
print(arr3)

# Shapes, sizes, dtypes
print(arr1.shape, arr1.size, arr1.dtype)
print(arr2.shape, arr2.size, arr2.dtype)
print(arr3.shape, arr3.size, arr3.dtype)


[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[0.85106881 0.79437642 0.59468714]
  [0.8823318  0.54997169 0.64950588]
  [0.51651396 0.13174898 0.06176648]
  [0.86379318 0.03491625 0.59090461]
  [0.10798989 0.53076825 0.45774839]]

 [[0.46380473 0.05136123 0.22467657]
  [0.59608119 0.94428714 0.75589515]
  [0.04821424 0.72175833 0.76389407]
  [0.1435489  0.93507876 0.93958122]
  [0.19295932 0.14452261 0.68125768]]

 [[0.0279781  0.22514647 0.46724315]
  [0.93068945 0.41881902 0.17046427]
  [0.91257237 0.66809581 0.85669598]
  [0.4719247  0.42851566 0.8598432 ]
  [0.60431524 0.11187013 0.49881319]]]
(10,) 10 int64
(3, 3) 9 int64
(3, 5, 3) 45 float64


In [4]:
#Array Indexing and Slicing
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print(data[:3])          # First three elements
print(data[::2])         # Every alternate element
print(data[::-1])        # Reverse


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [5]:
# Mathematical Ops
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

print("A:", A)
print("B:", B)

print("Add:", A + B)
print("Subtract:", A - B)
print("Multiply:", A * B)
print("Divide:", A / B)

print("Dot Product:", np.dot(A, B))

print("A Mean:", np.mean(A))
print("A Median:", np.median(A))
print("A Std:", np.std(A))
print("A Var:", np.var(A))

print("B Max:", np.max(B), "at index", np.argmax(B))
print("B Min:", np.min(B), "at index", np.argmin(B))


A: [ 3  7 13 16 16]
B: [ 7  4 16 14  3]
Add: [10 11 29 30 19]
Subtract: [-4  3 -3  2 13]
Multiply: [ 21  28 208 224  48]
Divide: [0.42857143 1.75       0.8125     1.14285714 5.33333333]
Dot Product: 529
A Mean: 11.0
A Median: 13.0
A Std: 5.176871642217914
A Var: 26.8
B Max: 16 at index 2
B Min: 3 at index 4


In [6]:
# Reshaping And Trnasposing
arr = np.arange(1, 13)

arr2d = arr.reshape(4, 3)
print(arr2d)

arr3d = arr.reshape(2, 2, 3)
print(arr3d)

transposed = arr2d.T
print(transposed)
print("Transposed shape:", transposed.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Transposed shape: (3, 4)


In [7]:
# Boolean masking and filtering 
arr = np.random.randint(10, 51, 15)
print("Array:", arr)

print("Elements >25:", arr[arr > 25])

arr[arr < 30] = 0
print("After replacing <30 with 0:", arr)

print("Count divisible by 5:", np.sum(arr % 5 == 0))


Array: [24 46 24 13 35 34 45 35 23 37 33 27 32 47 16]
Elements >25: [46 35 34 45 35 37 33 27 32 47]
After replacing <30 with 0: [ 0 46  0  0 35 34 45 35  0 37 33  0 32 47  0]
Count divisible by 5: 9


In [8]:
# Working with built in functions
print(np.linspace(0, 1, 10))

print(np.eye(4))

arr = np.random.randint(1, 101, 20)
arr.sort()
print("Sorted:", arr)
print("5 largest:", arr[-5:])


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sorted: [ 2 11 15 16 17 23 32 39 42 42 49 54 55 60 61 66 71 79 86 95]
5 largest: [66 71 79 86 95]
